### ISSUE TITLE
PHP5.6 required

### ISSUE THREAD

**Issue by thiagotalma** [pgaultier/yii2-redis-rbac#1]
You can change to 5.5.9, which is the official version of Ubuntu 14.04?

Thanks!

**Comment by pgaultier** [comment]
Hi,
Target version won't be change to PHP5.5 because 
- PHP5.5 is in end of life http://php.net/supported-versions.php
- Many test tools we use require PHP5.6

Anyway, you can fork it and adjust it to make it PHP5.5 compatible
